### ISSUE TITLE
More test distributions + other sort algos

### ISSUE THREAD

**Issue by bourgesl** [sebawild/nearly-optimal-mergesort-code#1]
I started studying both your paper and its code.
I will add more test distributions: reversed runs, more almost sorted data.
I tested on small arrays 1000 to 100 000 and figured out that TopDownMergeSort wins. Moreover I will include my own MergeSort (no alloc) to compare with:
https://github.com/bourgesl/marlin-renderer/blob/openjdk/src/main/java/sun/java2d/marlin/MergeSort.java

I am looking for an optimized sort for edge data. QSorte (MainWright 87) is faster when size > 10000, but it is not stable and its worst case is O(n2)...

**Comment by bourgesl** [comment]
Excellent, I will prepare a Pull Request to add new test distributions.

I started playing with your benchmark and figured out that BottomUpMergeSort is great when size in [1000; 100 000] (random, runs 30, timesort drag 32), but dual pivot quicksort is the overall winner; sorry for your new power / peek sorts that behaves better on sorted runs:
- inputs = random-permutations
```
avg-ms=0.37163013,	 algo=Arrays.sort(int[]), n=5000     (2503501)	(n=1000, µ=0.37163013, σ=0.020347243)
avg-ms=0.4096248,	 algo=BottomUpMergesort+minRunLen=24+checkSorted=true, n=5000     (2503501)	(n=1000, µ=0.4096248, σ=0.018832253)
avg-ms=0.45564678,	 algo=MarlinSort+USE_QSORT=false+USE_QSORTE=false, n=5000     (2503501)	(n=1000, µ=0.45564678, σ=0.01943644)
avg-ms=0.4631984,	 algo=PeekSort+iscutoff=24+onlyIncRuns=false, n=5000     (2503501)	(n=1000, µ=0.4631984, σ=0.052792095)
avg-ms=0.46974096,	 algo=PowerSort+minRunLen=24+msb=true+onlyIncRuns=false, n=5000     (2503501)	(n=1000, µ=0.46974096, σ=0.19252217)
avg-ms=0.49999237,	 algo=TopDownMergesort+iscutoff=24+checkSorted=true, n=5000     (2503501)	(n=1000, µ=0.49999237, σ=0.021370906)
avg-ms=0.6104609,	 algo=TimsortTrot, n=5000     (2503501)	(n=1000, µ=0.6104609, σ=0.022363223)
```
- inputs = runs-with-exp-len-30
```
avg-ms=0.3035631,	 algo=PeekSort+iscutoff=24+onlyIncRuns=false, n=5000     (2503501)	(n=1000, µ=0.3035631, σ=0.047311153)
avg-ms=0.30781773,	 algo=BottomUpMergesort+minRunLen=24+checkSorted=true, n=5000     (2503501)	(n=1000, µ=0.30781773, σ=0.014322015)
avg-ms=0.31614432,	 algo=PowerSort+minRunLen=24+msb=true+onlyIncRuns=false, n=5000     (2503501)	(n=1000, µ=0.31614432, σ=0.01631012)
avg-ms=0.3259877,	 algo=Arrays.sort(int[]), n=5000     (2503501)	(n=1000, µ=0.3259877, σ=0.01437328)
avg-ms=0.3275299,	 algo=TimsortTrot, n=5000     (2503501)	(n=1000, µ=0.3275299, σ=0.017587412)
avg-ms=0.38631377,	 algo=TopDownMergesort+iscutoff=24+checkSorted=true, n=5000     (2503501)	(n=1000, µ=0.38631377, σ=0.016195783)
avg-ms=0.3876843,	 algo=MarlinSort+USE_QSORT=false+USE_QSORTE=false, n=5000     (2503501)	(n=1000, µ=0.3876843, σ=0.015585799)
```
- inputs = timsort-drag-minRunLen-32
```
avg-ms=0.2711976,	 algo=TimsortTrot, n=5000     (2503501)	(n=1000, µ=0.2711976, σ=0.011732268)
avg-ms=0.27778953,	 algo=PowerSort+minRunLen=24+msb=true+onlyIncRuns=false, n=5000     (2503501)	(n=1000, µ=0.27778953, σ=0.013121041)
avg-ms=0.2814509,	 algo=PeekSort+iscutoff=24+onlyIncRuns=false, n=5000     (2503501)	(n=1000, µ=0.2814509, σ=0.013248763)
avg-ms=0.3179316,	 algo=BottomUpMergesort+minRunLen=24+checkSorted=true, n=5000     (2503501)	(n=1000, µ=0.3179316, σ=0.014136404)
avg-ms=0.32710198,	 algo=Arrays.sort(int[]), n=5000     (2503501)	(n=1000, µ=0.32710198, σ=0.015955875)
avg-ms=0.37800008,	 algo=MarlinSort+USE_QSORT=false+USE_QSORTE=false, n=5000     (2503501)	(n=1000, µ=0.37800008, σ=0.017130608)
avg-ms=0.39165863,	 algo=TopDownMergesort+iscutoff=24+checkSorted=true, n=5000     (2503501)	(n=1000, µ=0.39165863, σ=0.016128527)
```
PS: MarlinSort / BottomUpSort are not allocating extra space, an extra array is reused (for better performance and avoid gc):
```
    // avoid alloc
    private int[] aux = null;

    @Override
    public void sort(final int[] A, final int left, final int right) {
        if (doSortedCheck) {
            if (aux == null || aux.length < A.length) {
                aux = new int[A.length];
            }
            mergesortCheckSorted(A, left, right, aux);
        } else {
            mergesort(A, left, right);
        }
    }
```
PS: Such preallocation can be generalized to all sorting methods to avoid the GC overhead at all. I will test with `-verbose:gc`...

**Comment by sebawild** [comment]
I wanted to mention that I found results for such small array sizes as n=10k quite unreliable. Also in the numbers above, the standard deviation is of similar magnitude as are the differences between the algorithms ...

**Comment by bourgesl** [comment]
Good point, I will check sigma, probably related to GC, compilation or just data distribution causing good/bad pivot selection or hazard...

**Comment by bourgesl** [comment]
Looking at previous numbers, sigma ~ 0.02 max for avg ~ 0.3 ms (runs30 size=5000) ie 6%, that's not so bad estimates.
So sigma is not of similar magnitude, 1 magnitude less.
I agree that the average difference are often within 1 or 2 sigmas, so the trend is less clear. 
I will check GC overhead and increase the repeat count to reduce the variance in the future.

**Comment by bourgesl** [comment]
I wonder if JMH could be used to properly perform microbenchmarks...
I hacked your test code to minimize GC overhead and I confirm that tests with size < 5000 are unreliable: spread ~ 200%

**Comment by bourgesl** [comment]
Sebastian, I forked your repository and pushed this morning my latest changes (including new sorts MarlinSort, DualPivotQuicksort, DualPivotQuicksort2018) + benchmark fixes (GC, better average for small arrays ie added an inner loops). As it is preliminary, I will do more cleanup before submitting you a PR:
https://github.com/bourgesl/nearly-optimal-mergesort-code

I published also first results:
https://github.com/bourgesl/nearly-optimal-mergesort-code/tree/master/results

**Comment by bourgesl** [comment]
Vladimir Yaroslavskiy shared its sort benchmarks:
http://mail.openjdk.java.net/pipermail/core-libs-dev/2018-November/056572.html

I will have a look...

**Comment by bourgesl** [comment]
Hi Sebastian,
I integrated DPQS 2018 from Vladimir and bentley basher (lots of int distributions) into my fork:
https://github.com/bourgesl/nearly-optimal-mergesort-code

I got a pull request to have a RadixSort and it is the overall winner on ints !!

**Comment by sebawild** [comment]
Hi Laurent,
I'm not surprised that radix sort performs well as long as the input and auxiliary array fit in cache; it is a good algorithm and avoids also branches.  For larger inputs, the non-sequential memory accesses will hurt though.  Did you try inputs sizes beyond L3 cache size?

**Comment by bourgesl** [comment]
Good point,
I will try 10m ints, ie 40mb to test that.
Possibly, another hybrid radix + merge sort could be done to merge parts sorted by radix sort (in cache < 1mb)...

I will try writing my radixSort dealing wigh 2 words (sort + indice) where only sort is used by radix sort.

I integrated bentley's basher and I am studying its results...

**Comment by bourgesl** [comment]
FYI I made lots of improvements in my fork, I updated the Readme to explain my morivations & objectives...
See https://github.com/bourgesl/nearly-optimal-mergesort-code/blob/master/README.md
I will then make comparison plots and try JMH to cross validate my results.
Bye
